### ISSUE TITLE
marker does not point anywere

### ISSUE THREAD

**Issue by 88-percent** [tmalsburg/helm-org-contacts#9]
This is a great tool when it works, but after I've called it a few times I start getting the following error in the minibuffer:

marker does not point anywhere

**Comment by tmalsburg** [comment]
Hey, thanks.  In my setup, this package doesn't work at all at this time.  I stopped maintaining it when I realized that it's not catching on.  Supporting my other packages, some of which have seen more success, also used up the little time I had available for such side projects.

I should perhaps try to revive this thing.  Proper contact management is definitely something that's missing in my otherwise fairly complete Emacs setup.

Last time I checked, one big weakness of the org-contacts approach was, that there was no reliable two-way syncing with CardDAV servers.  But of course it would be awfully nice to have the same address book in Emacs and on my phone.  Perhaps there is better support for this now.  Not sure.

**Comment by 88-percent** [comment]
When looking at emacs packages with little activity I sometimes find it difficult to determine if the package is no longer maintained or if the package is simply is so solid that there hasn't been any need for further issues or commits. I'm sorry to hear its the former in this case - this package really was the missing link that would have allowed full integration between emacs and a contacts list.

While I'd certainly have a use case for the revival of this project myself, I can't in good conscious pretend any further work on this project would be a productive use of your time. From my understanding there still is no reliable CardDAV sync.

I think the best chance for syncing may be to have an [Orgzly](https://github.com/orgzly/orgzly-android/issues/724) fork incorporate some contacts list functionality. For now, I'm making due with [org-vcard](https://github.com/flexibeast/org-vcard) (also, unfortunately, unmaintained).

Thanks so much for your work.
